image: Visual Studio 2017
build_script:
 - nuget restore
 - nuget install OpenCover -OutputDirectory packages -Version 4.6.519
 - dotnet build TestBLwithWebRequest.sln
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test C:\projects\test-bl-with-webrequest\BL.Tests\BL.Tests.csproj" -output:"coverage.xml" -filter:"+[BL*]* -[BL.Tests*]*" -oldStyle
after_test:
 - ps: |
    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
    bash codecov.sh -f "coverage.xml"
